Razor/Razor/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Razor.Models
{
    public class Categoria
    {
        public string Nome { get; set; }
        public Categoria(string nome)
        {
            this.Nome = nome;
        }
    }
}

Razor/Razor/Models/Departamento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Razor.Models
{
    public class Departamento
    {
        public string Nome { get; set; }
        public List<Categoria> Categorias { get; set; } = new List<Categoria>();
    }
}

Razor/Razor/Models/Estado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Razor.Models
{
    public enum Estado 
    {
        AC, AL, AP, AM,
        BA, CE, DF, ES,
        GO, MA, MT, MS,
        MG, PR, PB, PA,
        PE, PI, RJ, RN,
        RS, RO, RR, SC,
        SE, SP, TO
    }
}

Razor/Razor/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Razor.Models
{
    public class Produto
    {
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public decimal Preco { get; set; }

        public Produto(string nome, string descricao, decimal preco)
        {
            this.Nome = nome;
            this.Descricao = descricao;
            this.Preco = preco;
        }
    }
}

Razor/Razor/Models/Sexo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Razor.Models
{
    public enum  Sexo 
    {
        Masculino = 'M',
        Femenino = 'F'
    }
}

Razor/Razor/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Razor.Models
{
    public class Usuario
    {
        public virtual int Id { get; set; }

        [Required]
        public virtual String Nome { get; set; }

        [Required, EmailAddress]
        public virtual String Email { get; set; }

        [Required, MinLength(100)]
        public virtual String Senha { get; set; }
        
        public virtual String Sexo { get; set; }

        public virtual String Estado { get; set; }

        [Required]
        public virtual DateTime DataNascimento { get; set; }

        [Required]
        public virtual String Endereco { get; set; }

        public virtual String Complemento { get; set; }

        [Required, RegularExpression("\\d{5}-\\d{3}")]
        public virtual  String Cep { get; set; }
  
    }
}

Razor/Razor/Controllers/AutenticacaoController.cs
using DAL.Infra;
using NHibernate;
using Razor.DAO;
using Razor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Razor.Controllers
{
    public class AutenticacaoController : Controller
    {
        private ISession session;
        private UsuariosDAO usuarioDao;

        public AutenticacaoController()
        {
            session = NHibernateHelper.OpenSession();
            usuarioDao = new UsuariosDAO(session);
        }
        // GET: Autenticacao
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Autentica(string email, string senha)
        {
           
            Usuario usuarioLogado = usuarioDao.Login(email, senha);
            if (usuarioLogado != null)
            {
                Session["usuarioLogado"] = usuarioLogado.Nome;
                return RedirectToAction("Index", "Home");
            }
            return View("Index");
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

Razor/Razor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Razor.Models;
using Razor.DAO;

namespace Razor.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ProtudosDAO produtosDAO = new ProtudosDAO();
            ViewBag.Produtos = produtosDAO.Ofertas();
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contato()
        {
            return View();
        }

    }
}

Razor/Razor/Controllers/MenuController.cs
using Razor.DAO;
using Razor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Razor.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public ActionResult Index()
        {
            DepartamentosDAO departamentosDAO = new DepartamentosDAO();
            ViewBag.Departamentos = departamentosDAO.Lista();

            return View();
        }

    }
}

Razor/Razor/Controllers/UsuariosController.cs
using DAL.Infra;
using NHibernate;
using Razor.DAO;
using Razor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Razor.Controllers
{
    public class UsuariosController : Controller
    {
         private ISession session;
         private UsuariosDAO usuarioDao;

         public UsuariosController()
        {
            session = NHibernateHelper.OpenSession();
            usuarioDao = new UsuariosDAO(session);
        }

        // GET: Usuario
        public ActionResult Form(string email)
        {
            Usuario u = new Usuario()
            {
                Email = email
            };
            return View(u);
        }

        [HttpPost]
        public ActionResult BuscarUsuario(string email, string senha)
        {
            var usuario = usuarioDao.Login(email, senha);

            return View("Home", usuario);
        }

        [HttpPost]
        public ActionResult Cadastrar(Usuario usuario)
        {
            if (ModelState.IsValid)
            {

                usuarioDao.Adiciona(usuario);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View("Form", usuario);
            }
        }
    }
}

Razor/Razor/Views/Autenticacao/Index.cshtml
@using System.Web.Optimization;

<div class="hero-unit span6">

    <h2>Login</h2>
    <p>Já Possui Cadastro? Então faça seu login</p>
    <form action="@Url.Action("Autentica", "Autenticacao")" method="post">
        <input type="text" name="email" class="input-block-level" placeholder="E-mail" required />
        <input type="password" name="senha" class="input-block-level" placeholder="Senha" required />
        <input type="submit" class="btn btn-large btn-primary" value="Fazer Login" />
    </form>
</div>
<div class="hero-unit span6">
    <h2>Novo Usuário?</h2>
    <p>Se você ainda não tem um cadastro, informe qual é o e-mail que você deseja associar com sua conta</p>
    <form action="@Url.Action("Form", "Usuarios")">
        <input type="text" class="input-block-level" placeholder="E-mail" name="Email" />
        <input type="submit" class="btn btn-large btn-primary" value="Criar Conta" />
    </form>
</div>

Razor/Razor/Views/Home/Index.cshtml
<!-- conteúdo -->
<div class="hero-unit">
    <h1>Queima de estoque</h1>
    <p>Monitores com 20% de desconto no cartão de crédito em 50 vezes sem juros</p>
</div>
<div class="row-fluid">
    <!-- produtos aqui -->
    @foreach (var produto in ViewBag.Produtos)
    {
        <div class="span4">
            <p>@produto.Nome</p>
            <p>@produto.Descricao</p>
            <p>@produto.Preco</p>
        </div>
    }
</div>

               

Razor/Razor/Views/Menu/Index.cshtml
@{
    Layout = null;
}
<div class="sidebar-nav well">
    <ul class="nav nav-list">
        @foreach (var departamento in ViewBag.Departamentos)
        {
            <li class="nav-header">@departamento.Nome</li>
            foreach (var categoria in departamento.Categorias)
            {
                <li>@categoria.Nome</li>
            }
        }
    </ul>
</div>

Razor/Razor/Views/Shared/Erro.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <h2>
        Sorry, an error occurred while processing your request.
    </h2>
</body>
</html>

Razor/Razor/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;

<!DOCTYPE html>
<html>
<head>
    @Styles.Render("~/bundles/styles")
    @section Scripts
    {
        @Scripts.Render("~/bundles/scripts")
    }
</head>
<body>
    @Html.Partial("_MenuSuperior")
    <div class="span3">
        <!-- menu -->
        @Html.Action("Index", "Menu")
    </div>
    <div class="span9">
        @RenderBody()
    </div>
    @RenderSection("Scripts", false)
</body>
</html>

Razor/Razor/Views/Shared/_MenuSuperior.cshtml
@using Razor.Internacionalizacao
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        @Html.ActionLink("Loja Razor", "Index", "Home", null, new { @class = "brand" })
        <ul class="nav">
            <li>@Html.ActionLink(Mensagens.Sobre, "About", "Home")</li>
            <li>@Html.ActionLink(Mensagens.Contato, "Contato", "Home")</li>
        </ul>
        <p class="navbar-text pull-right">
            @if (Session["usuarioLogado"] != null)
            {
                @Mensagens.BemVindo
                @(" " + Session["usuarioLogado"] + " " )
                @Html.ActionLink("Logout", "Logout", "Autenticacao")
            }
            else
            {
                @Mensagens.OlaVisitante 
                @Html.ActionLink(Mensagens.Login, "Index", "Autenticacao")
                @:ou
                @Html.ActionLink(Mensagens.CadastreSe, "Form", "Usuarios")
            }
        </p>
    </div>
</div>

http://www.leandroprado.com.br/2010/11/mapeamento-many-to-many-com-nhibernate/

Razor/Razor/Views/Usuarios/Form.cshtml
@model Razor.Models.Usuario

@using (Html.BeginForm("Cadastrar", "Usuarios", FormMethod.Post))
{
    <fieldset>
        <legend>Dados Pessoais</legend>
        <div class="form-group">
            @Html.LabelFor(usuario => usuario.Nome, "Nome:")
            @Html.TextBoxFor(usuario => usuario.Nome, new { @class = "input-block-level" })
            @Html.ValidationMessageFor(usuario => usuario.Nome)
        </div>
        <div class="form-group">

            @Html.LabelFor(u => u.Email, "Email:")
            @Html.TextBoxFor(u => u.Email, new { @class = "input-block-level" })
            @Html.ValidationMessageFor(u => u.Email)
        </div>
        <div class="form-group">
            @Html.LabelFor(u => u.Senha, "Senha:")
            @Html.PasswordFor(u => u.Senha, new { @class = "input-block-level" })
            @Html.ValidationMessageFor(u => u.Senha)
        </div>
        <div class="form-group">
            @Html.LabelFor(u => u.DataNascimento, "Data de Nascimento:")
            @Html.TextBoxFor(u => u.DataNascimento, new { @class = "input-block-level" })
            @Html.ValidationMessageFor(u => u.DataNascimento)
        </div>
        <div class="form-group">
            <label class="inline radio">
                @Html.RadioButtonFor(u => u.Sexo, Convert.ToChar(Razor.Models.Sexo.Masculino).ToString()) @Razor.Models.Sexo.Masculino.ToString()
            </label>
            <label class="inline radio">
                @Html.RadioButtonFor(u => u.Sexo, Convert.ToChar(Razor.Models.Sexo.Femenino).ToString()) @Razor.Models.Sexo.Femenino.ToString()
            </label>
        </div>
        <div class="form-group">
            @Html.LabelFor(usuario => usuario.Estado, "Estado:")
            @Html.DropDownListFor(u => u.Estado, new SelectList(Enum.GetValues(typeof(Razor.Models.Estado))), new { @class = "input-block-level" })
        </div>
</fieldset>
    <fieldset>
        <legend>Dados de Entrega</legend>
        @Html.LabelFor(u => u.Endereco, "Endereço:")
        @Html.TextBoxFor(u => u.Endereco, new { @class = "input-block-level" })
        @Html.ValidationMessageFor(u => u.Endereco)

        @Html.LabelFor(u => u.Complemento, "Complemento:")
        @Html.TextBoxFor(u => u.Complemento, new { @class = "input-block-level" })
        @Html.ValidationMessageFor(u => u.Complemento)

        @Html.LabelFor(u => u.Cep, "CEP:")
        @Html.TextBoxFor(u => u.Cep, new { @class = "input-block-level" })
        @Html.ValidationMessageFor(u => u.Cep)
    </fieldset>
   
    <input type="submit" value="Cadastrar" class="btn btn-large" />
}